default_model = "ClaudeBedrockSonnet45"
chat_default_model = "ClaudeBedrockSonnet45"
terminal_default_model = "KimiK25"
conductor_default_model = "ClaudeBedrockOpus46"
summarizer_default_model = "ZaiGLM47Flash"
allow_request_override = true

allowed_models = [
  "ClaudeBedrockOpus46",
  "ClaudeBedrockSonnet45",
  "ClaudeBedrockHaiku45",
  "ZaiGLM47",
  "ZaiGLM47Flash",
  "ZaiGLM47Air",
  "KimiK25"
]

chat_allowed_models = [
  "ClaudeBedrockSonnet45",
  "ClaudeBedrockHaiku45",
  "ZaiGLM47Flash",
  "ZaiGLM47",
  "KimiK25"
]

terminal_allowed_models = [
  "KimiK25",
  "ZaiGLM47",
  "ZaiGLM47Flash"
]

conductor_allowed_models = [
  "ClaudeBedrockOpus46",
  "ClaudeBedrockSonnet45",
  "ZaiGLM47"
]

summarizer_allowed_models = [
  "ZaiGLM47Flash",
  "ClaudeBedrockHaiku45"
]
